name: Deploy README as GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Copy README to index.md
        run: cp README.md index.md

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages

    runs-on: ubuntu-latest

    steps:
      - uses: actions/deploy-pages@v4
